// Export pages
export '/welcomepage/home_page/home_page_widget.dart' show HomePageWidget;
export '/auth/signinpage/signinpage_widget.dart' show SigninpageWidget;
export '/auth/signuppage/signuppage_widget.dart' show SignuppageWidget;
export '/utilities/userprofile/userprofile_widget.dart' show UserprofileWidget;
export '/auth/forgetpasswordpage/forgetpasswordpage_widget.dart'
    show ForgetpasswordpageWidget;
export '/homepage/dashboard/dashboard_widget.dart' show DashboardWidget;
export '/utilities/settings/settings_widget.dart' show SettingsWidget;
export '/utilities/editprofile/editprofile_widget.dart' show EditprofileWidget;
export '/science_questions/science_q1/science_q1_widget.dart'
    show ScienceQ1Widget;
export '/science_questions/q2/q2_widget.dart' show Q2Widget;
export '/science_questions/q3/q3_widget.dart' show Q3Widget;
export '/science_questions/q4/q4_widget.dart' show Q4Widget;
export '/science_questions/q5/q5_widget.dart' show Q5Widget;
export '/science_questions/q6/q6_widget.dart' show Q6Widget;
export '/science_questions/q7/q7_widget.dart' show Q7Widget;
export '/science_questions/q8/q8_widget.dart' show Q8Widget;
export '/science_questions/q9/q9_widget.dart' show Q9Widget;
export '/science_questions/q10/q10_widget.dart' show Q10Widget;
export '/science_questions/score_page/score_page_widget.dart'
    show ScorePageWidget;
export '/kids_special/k_score/k_score_widget.dart' show KScoreWidget;
export '/eniglish_questions/e_score/e_score_widget.dart' show EScoreWidget;
export '/sport_questions/s_score/s_score_widget.dart' show SScoreWidget;
export '/gk/g_k_score/g_k_score_widget.dart' show GKScoreWidget;
export '/math_questions/m_score/m_score_widget.dart' show MScoreWidget;
export '/math_questions/mq1/mq1_widget.dart' show Mq1Widget;
export '/gk/gkq1/gkq1_widget.dart' show Gkq1Widget;
export '/sport_questions/sq1/sq1_widget.dart' show Sq1Widget;
export '/eniglish_questions/eq1/eq1_widget.dart' show Eq1Widget;
export '/kids_special/kq1/kq1_widget.dart' show Kq1Widget;
export '/math_questions/mq2/mq2_widget.dart' show Mq2Widget;
export '/math_questions/mq3/mq3_widget.dart' show Mq3Widget;
export '/math_questions/mq4/mq4_widget.dart' show Mq4Widget;
export '/math_questions/mq5/mq5_widget.dart' show Mq5Widget;
export '/math_questions/mq6/mq6_widget.dart' show Mq6Widget;
export '/math_questions/mq7/mq7_widget.dart' show Mq7Widget;
export '/math_questions/mq8/mq8_widget.dart' show Mq8Widget;
export '/math_questions/mq9/mq9_widget.dart' show Mq9Widget;
export '/math_questions/mq10/mq10_widget.dart' show Mq10Widget;
export '/gk/gkq2/gkq2_widget.dart' show Gkq2Widget;
export '/gk/gkq3/gkq3_widget.dart' show Gkq3Widget;
export '/gk/gkq4/gkq4_widget.dart' show Gkq4Widget;
export '/gk/gkq5/gkq5_widget.dart' show Gkq5Widget;
export '/gk/gkq6/gkq6_widget.dart' show Gkq6Widget;
export '/gk/gkq7/gkq7_widget.dart' show Gkq7Widget;
export '/gk/gkq8/gkq8_widget.dart' show Gkq8Widget;
export '/gk/gkq9/gkq9_widget.dart' show Gkq9Widget;
export '/gk/gkq10/gkq10_widget.dart' show Gkq10Widget;
export '/sport_questions/sq2/sq2_widget.dart' show Sq2Widget;
export '/sport_questions/sq3/sq3_widget.dart' show Sq3Widget;
export '/sport_questions/sq4/sq4_widget.dart' show Sq4Widget;
export '/sport_questions/sq5/sq5_widget.dart' show Sq5Widget;
export '/sport_questions/sq6/sq6_widget.dart' show Sq6Widget;
export '/sport_questions/sq7/sq7_widget.dart' show Sq7Widget;
export '/sport_questions/sq8/sq8_widget.dart' show Sq8Widget;
export '/sport_questions/sq9/sq9_widget.dart' show Sq9Widget;
export '/sport_questions/sq10/sq10_widget.dart' show Sq10Widget;
export '/eniglish_questions/eq2/eq2_widget.dart' show Eq2Widget;
export '/eniglish_questions/eq3/eq3_widget.dart' show Eq3Widget;
export '/eniglish_questions/eq4/eq4_widget.dart' show Eq4Widget;
export '/eniglish_questions/eq5/eq5_widget.dart' show Eq5Widget;
export '/eniglish_questions/eq6/eq6_widget.dart' show Eq6Widget;
export '/eniglish_questions/eq7/eq7_widget.dart' show Eq7Widget;
export '/eniglish_questions/eq8/eq8_widget.dart' show Eq8Widget;
export '/eniglish_questions/eq9/eq9_widget.dart' show Eq9Widget;
export '/eniglish_questions/eq10/eq10_widget.dart' show Eq10Widget;
export '/kids_special/kq2/kq2_widget.dart' show Kq2Widget;
export '/kids_special/kq10/kq10_widget.dart' show Kq10Widget;
export '/kids_special/kq3/kq3_widget.dart' show Kq3Widget;
export '/kids_special/kq4/kq4_widget.dart' show Kq4Widget;
export '/kids_special/kq5/kq5_widget.dart' show Kq5Widget;
export '/kids_special/kq6/kq6_widget.dart' show Kq6Widget;
export '/kids_special/kq7/kq7_widget.dart' show Kq7Widget;
export '/kids_special/kq8/kq8_widget.dart' show Kq8Widget;
export '/kids_special/kq9/kq9_widget.dart' show Kq9Widget;
export '/utilities/supportpage/supportpage_widget.dart' show SupportpageWidget;
export '/utilities/termsandconditions/termsandconditions_widget.dart'
    show TermsandconditionsWidget;
